In [2]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\Prajwal\Downloads\Raw projects\customer_shopping_behavior.csv")

In [3]:
df.head

<bound method NDFrame.head of     Customer ID  Age  Gender Item Purchased  ... Promo Code Used  Previous Purchases Payment Method Frequency of Purchase
0             1   55    Male         Blouse  ...             Yes                  14          Venmo           Fortnightly
1             2   19    Male        Sweater  ...             Yes                   2           Cash           Fortnightly
2             3   50    Male          Jeans  ...             Yes                  23    Credit Card                Weekly
3             4   21    Male        Sandals  ...             Yes                  49         PayPal                Weekly
4             5   45    Male         Blouse  ...             Yes                  31         PayPal              Annually
..          ...  ...     ...            ...  ...             ...                 ...            ...                   ...
95           96   39  Female          Skirt  ...             Yes                  23         PayPal                Weekly
96           97   27    Male        T-Shirt  ...              No                   4           Cash             Quarterly
97           98   54  Female        Handbag  ...             Yes                  33    Credit Card           Fortnightly
98           99   41    Male          Jeans  ...             Yes                  20     Debit Card                Weekly
99          100   36  Female          Dress  ...             Yes                  25          Venmo               Monthly

[100 rows x 18 columns]>

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer ID            100 non-null    int64
 1   Age                    100 non-null    int64
 2   Gender                 100 non-null    str
 3   Item Purchased         100 non-null    str
 4   Category               100 non-null    str
 5   Purchase Amount        100 non-null    int64
 6   Location               100 non-null    str
 7   Size                   100 non-null    str
 8   Color                  100 non-null    str
 9   Season                 100 non-null    str
 10  Review Rating          100 non-null    float64
 11  Subscription Status    100 non-null    str
 12  Shipping Type          100 non-null    str
 13  Discount Applied       100 non-null    str
 14  Promo Code Used        100 non-null    str
 15  Previous Purchases     100 non-null    int64
 16  Payment Method         100 non-null    str
 17  Frequency of Purchase  100 non-null    str
dtypes: float64(1), int64(4), str(13)
memory usage: 14.2 KB

In [8]:
df.describe(include='all')

        Customer ID         Age Gender  ... Previous Purchases Payment Method  Frequency of Purchase
count    100.000000  100.000000    100  ...         100.000000            100                    100
unique          NaN         NaN      2  ...                NaN              6                      6
top             NaN         NaN   Male  ...                NaN           Cash                 Weekly
freq            NaN         NaN     54  ...                NaN             20                     29
mean      50.500000   43.040000    NaN  ...          23.300000            NaN                    NaN
std       29.011492   13.806688    NaN  ...          14.811612            NaN                    NaN
min        1.000000   19.000000    NaN  ...           2.000000            NaN                    NaN
25%       25.750000   30.750000    NaN  ...          10.000000            NaN                    NaN
50%       50.500000   42.500000    NaN  ...          21.500000            NaN                    NaN
75%       75.250000   55.000000    NaN  ...          34.250000            NaN                    NaN
max      100.000000   68.000000    NaN  ...          55.000000            NaN                    NaN

[11 rows x 18 columns]

In [10]:
df.isnull().sum()

Customer ID              0
Age                      0
Gender                   0
Item Purchased           0
Category                 0
Purchase Amount          0
Location                 0
Size                     0
Color                    0
Season                   0
Review Rating            0
Subscription Status      0
Shipping Type            0
Discount Applied         0
Promo Code Used          0
Previous Purchases       0
Payment Method           0
Frequency of Purchase    0
dtype: int64

In [11]:
# think as you have got some missing value in review rating 37 
# finding the median or mean of each category and replacing the missing value with the results 
''' 
df['Review Rating'] = df.group.by('category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

now check the null value once again 
'''

" \ndf['Review Rating'] = df.group.by('category')['Review Rating'].transform(lambda x: x.fillna(x.median()))\n\nnow check the null value once again \n"

In [12]:
# check the heading names and keep always heading names as lower case and don't use space insted use underscore 

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchase'],
      dtype='str')

In [14]:
# create a new column age_group 

labels = ['Young_Adult', 'Adult', 'Middle_Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [15]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle_Aged
1   19  Young_Adult
2   50  Middle_Aged
3   21  Young_Adult
4   45  Middle_Aged
5   46  Middle_Aged
6   63       Senior
7   27  Young_Adult
8   26  Young_Adult
9   57       Senior

In [17]:
# purchase frequency days - new columns 

frequency_maping = {
    'Fornightly': 14,
    'Weekly': 7, 
    'Monthly': 30, 
    'Quarterly': 90, 
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90 
}
df['purchase_frequency_days'] = df['frequency_of_purchase'].map(frequency_maping)

In [18]:
df[['purchase_frequency_days','frequency_of_purchase']].head(10)

   purchase_frequency_days frequency_of_purchase
0                      NaN           Fortnightly
1                      NaN           Fortnightly
2                      7.0                Weekly
3                      7.0                Weekly
4                    365.0              Annually
5                      7.0                Weekly
6                     90.0             Quarterly
7                      7.0                Weekly
8                    365.0              Annually
9                     90.0             Quarterly

In [20]:
(df[['discount_applied', 'promo_code_used']].head(101)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
..              ...             ...
95              Yes             Yes
96               No              No
97              Yes             Yes
98              Yes             Yes
99              Yes             Yes

[100 rows x 2 columns]

In [21]:
(df['discount_applied']==df['promo_code_used']).all()

np.False_

In [23]:
df = df.drop('promo_code_used',axis =1)

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchase', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [25]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\prajwal\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 3.1 MB/s eta 0:00:01
   ----------- ---------------------------- 0.8/2.8 MB 1.8 MB/s eta 0:00:02
   ------------------ --------------------- 1.3/2.8 MB 2.0 MB/s eta 0:00:01
   ------------------------- -------------- 1.8/2.8 MB 2.0 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.8 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.8 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 2.0 MB/s  0:00:01
Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.1 MB/s  0:00:00
Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl (239 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2-binary]
   ---------------------------------------- 0/3 [psycopg2-binary]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.1 psycopg2-binary-2.9.12 sqlalchemy-2.0.50
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: C:\Users\Prajwal\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [26]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\prajwal\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in c:\users\prajwal\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\prajwal\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: C:\Users\Prajwal\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [29]:
import pymysql
from sqlalchemy import create_engine 

username = "root"
password = "samiksha@#$123"
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}") 

table_name = "customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)

print(f"Data successfully loaded into table '{table_name}' in MySQL database '{database}'.")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '#$123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [30]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Define your credentials
username = "root"  # or whatever your username is
raw_password = "samiksha@#$123"

# 2. URL-encode the password to handle special characters (@, #) safely
password = urllib.parse.quote_plus(raw_password)

host = "localhost"
port = "3306"
database = "customer_behaviour"

# 3. Create the engine exactly as before
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# 4. Try running your to_sql again
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in MySQL database '{database}'.")

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)